language: python
python:
  - "3.9"
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12

#env:
#  global:
#    - PGPORT=5432
#    - PGUSER=voha
before_install:
  - sudo pg_dropcluster --stop 12 main
  - sudo pg_upgradecluster 11 main
  - sudo pg_ctlcluster 12 main restart
  - sudo pg_dropcluster 11 main

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - python manage.py test

branches:
  only:
    - main

deploy:
  - provider: heroku
    api_key: ad91dd46-4fa1-40cf-8c02-8afd228f809b
    app: provider-django-app

