# Generated by Django 3.2 on 2021-05-22 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('house_num', models.IntegerField()),
                ('apartment_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='WirelessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('days_to_connect', models.IntegerField()),
                ('description', models.TextField()),
                ('data_amount', models.IntegerField()),
                ('internet_type', models.CharField(choices=[('3G', '3G'), ('4G', '4G'), ('5G', '5G')], default='4G', max_length=2)),
                ('minutes_out', models.IntegerField()),
                ('minutes_abroad', models.IntegerField()),
                ('sms_amount', models.IntegerField()),
                ('connect_with_passport', models.BooleanField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TVPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('days_to_connect', models.IntegerField()),
                ('description', models.TextField()),
                ('quality', models.CharField(max_length=20)),
                ('channels_amount', models.IntegerField()),
                ('parent_control_available', models.BooleanField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('ordered_at', models.DateField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='InternetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('days_to_connect', models.IntegerField()),
                ('description', models.TextField()),
                ('connection_type', models.CharField(max_length=255)),
                ('speed', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.service')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='plans',
            field=models.ManyToManyField(related_name='related_customer', to='mainapp.OrderedPlan'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
