# Generated by Django 3.2 on 2021-05-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plans',
            field=models.ManyToManyField(null=True, related_name='related_customer', to='mainapp.OrderedPlan'),
        ),
    ]
