# Generated by Django 3.2 on 2021-05-22 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210522_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='related_customer', to='mainapp.OrderedPlan'),
        ),
        migrations.AlterField(
            model_name='orderedplan',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_plans', to='mainapp.customer'),
        ),
    ]
